apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmaiauth-demo
  namespace: irmaiauth-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irmaiauth-demo
  template:
    metadata:
      labels:
        app: irmaiauth-demo
    spec:
      containers:
        - name: irmaiauth-demo
          image: us-central1-docker.pkg.dev/midyear-lattice-455113-n7/irmai-artifact/irmaiauth-demo-module:latest
          ports:
            - containerPort: 8080
          
apiVersion: v1
kind: Service
metadata:
  name: irmaiauth-demo-module-service
  namespace: irmaiauth-demo
spec:
  selector:
    app: irmaiauth-demo-module
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
