apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmaiauth-demo-module
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: irmaiauth-demo
  template:
    metadata:
      labels:
        app: irmaiauth-demo-module
    spec:
      containers:
        - name: irmaiauth-demo-module
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
