apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmai-auth-module
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: irmai-auth
  template:
    metadata:
      labels:
        app: irmai-auth-module
    spec:
      containers:
        - name: irmai-auth-module
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}