apiVersion: v1
kind: Service
metadata:
  name: irmaiauth-demo-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: irmaiauth-demo-module
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}
