apiVersion: v1
kind: Service
metadata:
  name: irmai-auth-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: irmai-auth-module
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}